backend:
  name: github
  repo: vishal8005078-hash/ESTILO
  branch: main

media_folder: "images"

collections:
  - name: "products"
    label: "Products"
    files:
      - name: "products"
        label: "Product List"
        file: "index.html"
        fields:
          - {label: "Product Name", name: "name", widget: "string"}
          - {label: "Price", name: "price", widget: "string"}
          - {label: "Tag", name: "tag", widget: "string"}
          - {label: "Image URL", name: "image", widget: "string"}
